version: '3'

services:
  app:
    build: ./app
    volumes:
      - ./app:/src
    depends_on:
      - postgresdb
    tty: true

  postgresdb:
    image: postgres:10
    ports:
      - 15432:5432
    env_file:
      - ./config/postgres/db_env